### ISSUE TITLE
Version 3 dev plan - Tracker issue

### ISSUE THREAD

**Issue by webmaster442** [webmaster442/TCPlayer#35]
Playlist:
- [x] Multiple playlist support. Playlist should be independent of currently running engine playlist.
- [x] Introduce a PlaylistItemModel type to represent the playlist item in the Engine
- [x] Implement conversion between playlist item and Engine file based playlist
- [x] Playlist item has to have info for file path (resolved to absolute path), Metadata (single string to display)

Saving playlist:
- [x] Implement JSON based format to save the Playlist into a native format for the player
- [x] FileNames must be adapted to relative paths based on the save path
- [x] Implement a simple M3U saving with relative paths based on the save path

Now Playing:
- [ ] metadata should be annoted sohow to know data is artist name, year or etc...
- [ ] Display picture in the file name
- [ ] Display metadata
- [ ] Add command menus: youtube, discogs, soundcloud, spotify, wiki
- [ ] Each comand menu must contain the artist name, song title to search for the currently played song

Argument and file handling:
- [x] Implement a mutex based locking solution to prevent cration of an other instance of the running application
- [x] If the application is already running, then the args[] array, should be sent as a notification to the existing app.
- [x] Implement this behaviour as an extension of the WPF APP class

Auto update:
- [ ] Github client that scans github releases
- [ ] If release found newer than current version then download asset
- [ ] Asset is extracted to temp folder
- [ ] cmd script is generated to overwrite files
- [ ] Application exists and executes cmd script that overvwrites files
- [ ] cmd script deletes itself when done

**Comment by webmaster442** [comment]
Feel free to add requested features here

**Comment by webmaster442** [comment]
```csharp
public abstract class SingleInstanceAppClass : Application
{
    /// <summary>
    /// Application id. Must be unique
    /// </summary>
    public string? AppId { get; set; }

    private Mutex? _appLockMutex;
    private Thread? _namedPipeServer;
    private NamedPipeServerStream? _namedPipeServerStream;
    private CancellationTokenSource? _cancellationTokenSource;


    /// <summary>
    /// Startup argument handling. Executed when startup and when an other instance is started
    /// </summary>
    /// <param name="args">startup arguments</param>
    public abstract void HandleArguments(string[] args);

    protected override void OnStartup(StartupEventArgs e)
    {
        if (string.IsNullOrWhiteSpace(AppId))
            throw new InvalidOperationException("AppId is not set");

        string pipeName = $"{AppId}/pipe";

        base.OnStartup(e);
        if (Mutex.TryOpenExisting(AppId, out Mutex? capturedMutex))
        {
            var argumentsJson = JsonSerializer.Serialize(e.Args);
            using (var client = new NamedPipeClientStream(".", pipeName, PipeDirection.Out))
            {
                client.Connect();
                using (var writer = new StreamWriter(client, leaveOpen: true))
                {
                    writer.WriteLine(argumentsJson);
                }
                client.Close();
                Shutdown();
            }
        }
        else
        {
            _appLockMutex = new Mutex(false, AppId);
            _namedPipeServer = new Thread(NamedPipeListener);
            _namedPipeServerStream = new NamedPipeServerStream(pipeName, PipeDirection.In);
            _cancellationTokenSource = new CancellationTokenSource();
            _namedPipeServer.Start(_cancellationTokenSource.Token);
            HandleArguments(e.Args);
        }
    }

    private void NamedPipeListener(object? obj)
    {
        if (_namedPipeServerStream == null)
            throw new InvalidOperationException("Incorrect pipe setup");

        var token = (CancellationToken)obj!;
        while (!token.IsCancellationRequested)
        {
            _namedPipeServerStream.WaitForConnection();
            using (var reader = new StreamReader(_namedPipeServerStream, leaveOpen: true))
            {
                var json = reader.ReadToEnd();
                if (!string.IsNullOrEmpty(json))
                {
                    var args = JsonSerializer.Deserialize<string[]>(json) ?? Array.Empty<string>();
                    Dispatcher.Invoke(() => HandleArguments(args), System.Windows.Threading.DispatcherPriority.Input);
                }
            }
            _namedPipeServerStream.Disconnect();
        }
    }

    protected override void OnExit(ExitEventArgs e)
    {
        if (_namedPipeServer == null) return;
            
        _cancellationTokenSource?.Cancel();
        string pipeName = $"{AppId}/pipe";
        using (var client = new NamedPipeClientStream(".", pipeName, PipeDirection.Out))
        {
            client.Connect();
        }
        _namedPipeServerStream?.Dispose();
        _appLockMutex?.Dispose();
        _cancellationTokenSource?.Dispose();
    }
}
```
